### ISSUE TITLE
Not all selection channels are getting created on the bridge

### ISSUE THREAD

**Issue by pfink** [Wire82/org.openhab.binding.heos#9]
I have 3 players, but only two of them are added as selection channels, so I cannot create "overall" group containing all players. This is my configuration:

```
Bridge heos:bridge:98b89fbb-9611-44e0-ded5-362971a59d7d "HEOS Bridge (HEOS Amp: Wohnzimmer)" [ name="HEOS Amp", ipAddress="192.168.0.14", heartBeat=60] {
	Thing player 450590749 "HEOS Amp: Wohnzimmer" [ pid="450590749", type="Player", name="Wohnzimmer" ]
	Thing player 388435769 "Heos Link: Schlafzimmer" [ pid="388435769", type="Player", name="Schlafzimmer" ]
	Thing player -2050040747 "Heos 1: Badezimmer" [ pid="-2050040747", type="Player", name="Badezimmer" ]
}
```

The device "HEOS Amp: Wohnzimmer" is not getting added as a selection channel to the bridge, just "Heos Link: Schlafzimmer" and "Heos 1: Badezimmer". All player Things are getting created and working fine, just the selection channel on the bridge is missing.

**Comment by pfink** [comment]
Seemed to be a temporary issue, works fine now. I'll reopen if it occurs again.

**Comment by pfink** [comment]
This issue occurs sporadically. Sometimes after startup the all channels get created, sometimes not. I have to do further investigation to track the issue.

**Comment by pfink** [comment]
Within the log the following exception appears very often:

```
2017-04-18 21:18:50.577 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during bridge handler ('heos:bridge:98b89fbb-9611-44e0-ded5-362971a59d7d') notification about handler disposal of child 'heos:player:98b89fbb-9611-44e0-ded5-362971a59d7d:388435769': Could not update thing, because callback is missing
java.lang.IllegalStateException: Could not update thing, because callback is missing
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateThing(BaseThingHandler.java:447)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.openhab.binding.heos.handler.HeosBridgeHandler.removeChannel(HeosBridgeHandler.java:518)[193:org.openhab.binding.heos:0.1.6.-SNAPSHOT]
	at org.openhab.binding.heos.handler.HeosBridgeHandler.childHandlerDisposed(HeosBridgeHandler.java:247)[193:org.openhab.binding.heos:0.1.6.-SNAPSHOT]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$14.run(ThingManager.java:894)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
```

**Comment by pfink** [comment]
Log on startup where the issue occured:

```
2017-04-18 23:00:28.400 [INFO ] [nding.heos.handler.HeosBridgeHandler] - Inizialize child handler for: 388435769.
2017-04-18 23:00:28.434 [INFO ] [nding.heos.handler.HeosBridgeHandler] - Inizialize child handler for: -2050040747.
2017-04-18 23:00:28.503 [INFO ] [nding.heos.handler.HeosBridgeHandler] - Inizialize child handler for: 450590749.
2017-04-18 23:00:37.824 [INFO ] [io.openhabcloud.internal.CloudClient] - Shutting down openHAB Cloud service connection
2017-04-18 23:00:37.863 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = b6853989-bcb5-4127-b48d-d41643a47963, base URL = http://localhost:8080)
2017-04-18 23:00:38.223 [INFO ] [.openhab.binding.heos.api.HeosSystem] - HEOS System Event Listener is booting....
2017-04-18 23:00:38.252 [INFO ] [.openhab.binding.heos.api.HeosSystem] - HEOS System Event Listener is starting....
2017-04-18 23:00:38.256 [INFO ] [.openhab.binding.heos.api.HeosSystem] - HEOS System Event Listener succsessfully started
2017-04-18 23:00:38.274 [INFO ] [nding.heos.handler.HeosBridgeHandler] - HEOS System heart beat startet. Pulse time is 60s
2017-04-18 23:00:38.280 [ERROR] [nding.heos.handler.HeosBridgeHandler] - Can not log in. Username and Password not set
2017-04-18 23:00:42.179 [INFO ] [basic.internal.servlet.WebAppServlet] - Stopped Basic UI
2017-04-18 23:00:45.652 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-04-18 23:00:45.731 [INFO ] [ulation.internal.HueEmulationServlet] - Started Hue Emulation service at /api
2017-04-18 23:00:46.622 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = b6853989-bcb5-4127-b48d-d41643a47963, base URL = http://localhost:8080)
2017-04-18 23:01:22.559 [ERROR] [nding.heos.handler.HeosBridgeHandler] - Channel heos:bridge:98b89fbb-9611-44e0-ded5-362971a59d7d:P-2050040747 not found
2017-04-18 23:01:22.564 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_121]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:369)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.heos.handler.HeosBridgeHandler.handleCommand(HeosBridgeHandler.java:96)[193:org.openhab.binding.heos:0.1.6.-SNAPSHOT]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:372)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	... 5 more
2017-04-18 23:01:24.260 [INFO ] [ternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Player
2017-04-18 23:01:24.282 [INFO ] [ternal.discovery.HeosPlayerDiscovery] - Found: 3 new Player
2017-04-18 23:01:24.303 [INFO ] [ternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Groups
2017-04-18 23:01:24.313 [INFO ] [.openhab.binding.heos.api.HeosSystem] - Found: Group HEOS Schlafzimmer + HEOS Wohnzimmer with 2 Players
2017-04-18 23:01:24.316 [INFO ] [ternal.discovery.HeosPlayerDiscovery] - Found: 1 new Groups
2017-04-18 23:01:24.325 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'heos:group:4170950712' to inbox.
2017-04-18 23:01:25.819 [ERROR] [nding.heos.handler.HeosBridgeHandler] - Channel heos:bridge:98b89fbb-9611-44e0-ded5-362971a59d7d:P-2050040747 not found
2017-04-18 23:01:25.821 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_121]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:369)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.heos.handler.HeosBridgeHandler.handleCommand(HeosBridgeHandler.java:96)[193:org.openhab.binding.heos:0.1.6.-SNAPSHOT]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:372)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	... 5 more
2017-04-18 23:01:25.863 [WARN ] [nding.heos.handler.HeosBridgeHandler] - HEOS System response failure with error code '7' and message 'Command not executed'
2017-04-18 23:01:25.913 [WARN ] [nding.heos.handler.HeosBridgeHandler] - HEOS System response failure with error code '7' and message 'Command not executed'
2017-04-18 23:01:39.321 [ERROR] [nding.heos.handler.HeosBridgeHandler] - Channel heos:bridge:98b89fbb-9611-44e0-ded5-362971a59d7d:P-2050040747 not found
2017-04-18 23:01:39.323 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured while calling handler: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_121]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:188)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:81)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:65)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:369)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.items.events.AbstractItemEventSubscriber.receive(AbstractItemEventSubscriber.java:46)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:192)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:179)[98:org.eclipse.smarthome.core:0.9.0.b3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.heos.handler.HeosBridgeHandler.handleCommand(HeosBridgeHandler.java:96)[193:org.openhab.binding.heos:0.1.6.-SNAPSHOT]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:372)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$4.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.9.0.b3]
	... 5 more
2017-04-18 23:01:39.381 [WARN ] [nding.heos.handler.HeosBridgeHandler] - HEOS System response failure with error code '7' and message 'Command not executed'
2017-04-18 23:01:39.400 [WARN ] [nding.heos.handler.HeosBridgeHandler] - HEOS System response failure with error code '7' and message 'Command not executed'
```

**Comment by pfink** [comment]
I'm not sure but it seems like creating a group that includes all player with the bridge as the leader increases the probability that all selection channels are getting created properly.

**Comment by pfink** [comment]
I added a PR to fix this issue.

**Comment by Wire82** [comment]
@pfink Thank you! I merged the PR. Unfortunately I was not able to reproduce the issue.
The first log you send me is a typical error message if the binding or openhab is shutting down. It seems that the binding is trying to inform the bridge after it is getting offline.
Within the second log I see that the only issue is the player with a negative! PID. I'm surprised it that is possible.
But does the fix is working reliable?

**Comment by Wire82** [comment]
@pfink There was also a return statement missing if a channel is not found. This causes all the nullPointer as shown within your log...

**Comment by pfink** [comment]
Yeah, multithreading issues are typically hard to reproduce because their occurence highly depends on the hardware you're running, the scheduler behaviour and the number of threads (or in this specific case: the number of HEOS devices) you're using.

When developing, you should consider that ESH expects some methods to be thread-safe, and if they're not, crazy things can happen at any time and it's very hard to reproduce and track those issues. In those thread-safe methods, only thread-safe stuff should be done - which can be very tedious. E.g., even a normal HashMap is **not** thread-safe. But Java offers thread-safe alternatives for most stuff (like [ConcurrentHashMap](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html)). I'm not sure which methods exactly have to be thread-safe in ESH. But [this article](https://github.com/eclipse/smarthome/blob/master/docs/documentation/development/bindings/thing-handler.md) gives the hint that _handleCommand_ should also be thread-safe. Maybe you could check your code a little bit for other multithreading vulnerabilities :-) I'll also take a look within the next days.

A very safe option of bypassing the thread-safe requirement is putting methods to synchronized which means only one thread can access a method at the same time (which I did because I don't know if the addChannel method is thread-safe). But this also makes the program slower and it should not be used for operations that are may executed very often (so I'd not use it for the handleCommand method).

And yes, after applying the fix, issue did never occur again 👍 So I close this one.
